#!/usr/bin/env python
from RSBillManager import BillingRSClient

b = BillingRSClient() 
b.authenticate()
res = b.getBillingInfo()
print ("%-25s %3s %5s %5s %20s %5s\n" %("name", "diskspace", "bandwidthIn", "bandwidthOut", "uptime", "charges"))
totalDiskSpace = 0
totalBandIn = 0
totalBandOut = 0
totalCharges = 0

for f in res:
    print ("%-25s %3d %5.2f %5.2f %20s %5.2f " %(f.name, f.diskspace, f.bandwidth.inGB, f.bandwidth.outGB, f.uptime, f.charges))
    totalDiskSpace += f.diskspace
    totalBandIn += f.bandwidth.inGB
    totalBandOut += f.bandwidth.outGB
    totalCharges += f.charges


print ("\n%-25s %3d %5.2f %5.2f %20s %5.2f " %("Total:", totalDiskSpace, totalBandIn, totalBandOut, " - ", totalCharges))

